export const artists = [
  {
    id: 1,
    name: "Aryan Malik",
    bio: "Aryan is an emerging indie-pop singer known for heartfelt lyrics and soulful melodies.",
    image: "/image1.avif",
    category: "Singer",
    language: "Hindi, English",
    feeRange: "₹40,000 - ₹90,000",
    location: "Mumbai, India",
    email: "artist@gmail.com",
  },
  {
    id: 2,
    name: "Zara Sheikh",
    bio: "Zara is a classically trained vocalist blending Sufi and contemporary styles.",
    image: "/image2.avif",
    category: "Vocalist",
    language: "Urdu, Punjabi",
    feeRange: "₹50,000 - ₹1,00,000",
    location: "Delhi, India",
    email: "artist@gmail.com",
  },
  {
    id: 3,
    name: "Dev Mehra",
    bio: "Dev is a rising indie rock singer with a voice that resonates across generations.",
    image: "/image3.avif",
    category: "Singer",
    language: "Hindi",
    feeRange: "₹50,000 - ₹1,20,000",
    location: "Delhi, India",
    email: "artist@gmail.com",
  },

  {
    id: 4,
    name: "Ayaan Malik",
    bio: "Ayaan is a stand-up comedian known for his sharp wit and relatable humor.",
    image: "/image4.avif",
    category: "Comedian",
    language: "English",
    feeRange: "₹35,000 - ₹75,000",
    location: "Mumbai, India",
    email: "artist@gmail.com",
  },
  {
    id: 5,
    name: "Zara Shaikh",
    bio: "Zara is a soulful playback singer known for her mesmerizing classical renditions.",
    image: "/image5.avif",
    category: "Singer",
    language: "Urdu",
    feeRange: "₹60,000 - ₹1,10,000",
    location: "Lucknow, India",
    email: "artist@gmail.com",
  },
  {
    id: 6,
    name: "Ishita Roy",
    bio: "Ishita blends Kathak and contemporary dance to create electrifying performances.",
    image: "/image6.avif",
    category: "Dancer",
    language: "Bengali",
    feeRange: "₹40,000 - ₹90,000",
    location: "Kolkata, India",
    email: "artist@gmail.com",
  },
];
